books/book/urls.py
from django.conf.urls import include, url
from book import views
urlpatterns = [
    url(r'^$', views.index, name='index'),  # 首页
    url(r'^detail/(?P<id>.*)$',views.detail,name='detail'),
    url(r'^list/(?P<type_id>.+)/(?P<page>.+)$',views.list,name='list'),
]

books/books/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('register.urls', namespace='user')),
    url(r'^tinymce/',include('book.urls',namespace='book')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
]

books/register/urls.py
from django.conf.urls import include, url
from register import views
urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^login_handler/$',views.register_handler,name='register_handler'),
    url(r'^login/$',views.login,name='login'),
    url(r'^$', views.user,name = 'user'),
    url(r'^login_check/$',views.login_check,name='login_check'),
]

books/register/models.py
from django.db import models

# Create your models here.
from db.models import BaseModel
from utils.get_hash import get_hash

class passportManger(models.Manager):
	#添加用户数据
	def add_passport(self,user_name,user_pwd,email):
		port = self.create(user_name=user_name,user_pwd=get_hash(user_pwd),email=email)
		return port

	#获取用户数据
	def get_passport(self,user_name,user_pwd):
		try:
			port = self.get(user_name=user_name,user_pwd=user_pwd)
		except:
			port = None
		return port

class Passport(BaseModel):
	user_name = models.CharField(max_length=20,verbose_name='用户名',unique=True)
	user_pwd = models.CharField(max_length=40,verbose_name='密码')
	email = models.EmailField(verbose_name='邮箱')
	is_activr = models.BooleanField(default=False,verbose_name='状态')

	object = passportManger()

	class Meta:
		db_table = 'user_login'
class AddressManager(models.Manager):
	def get_default_address(self,passport_id):
		try:
			addr = self.get(passport_id=passport_id,is_default=True)
		except:
			addr = '没有收货地址'
		return addr
	def add_one_address(self,passport_id,recipient_name,recipient_addr,zip_code, recipient_phone):
		addr = self.get_default_address(passport_id=passport_id)
		if addr:
			is_default = False
		else:
			is_default = True

		addr =  self.create(passport_id=passport_id,
							recipient_name=recipient_name,
							recipient_addr = recipient_addr,
							recipient_phone = recipient_phone,
							zip_code = zip_code,
							is_default =is_default)
		return addr

class Address(BaseModel):
	recipient_name = models.CharField(max_length=20,verbose_name='收件人')
	recipient_addr = models.CharField(max_length=256,verbose_name='收件地址')
	zip_code = models.CharField(max_length=6,verbose_name='邮政编码')
	recipient_phone = models.CharField(max_length=11,verbose_name='联系电话')
	is_default = models.BooleanField(default=False,verbose_name='是否默认')
	passport = models.ForeignKey('passport',verbose_name='账户')

	object = AddressManager()

	class Meta:
		db_table = 's_user_address'

books/register/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
import re
from utils.get_hash import get_hash
from django.core.urlresolvers import reverse
# Create your views here.
from register.models import Passport,Address
from utils.login_required import login_required
def register(request):

	return render(request, 'register/register.html')
def register_handler(request):
	user_name = request.POST.get('user_name')
	user_pwd = request.POST.get('pwd')
	email = request.POST.get('email')

	if not all([user_pwd,user_name,email]):
		return render(request, 'register/register.html', {'errmsg': '参数不能为空'})
	if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$',email):
		return render(request, 'register/register.html', {'errmsg': '邮箱不合法'})

	Passport.object.add_passport(user_name,user_pwd,email)
	return redirect(reverse('book/book_details.html'))
def login_check(request):
	username = request.POST.get('username')
	password = request.POST.get('password')
	remember = request.POST.get('remember')

	if not all([username,password,remember]):
		return JsonResponse({'res':2})
	passport = Passport.object.get_passport(user_name = username , user_pwd = get_hash(password))
	print(username,get_hash(password),passport)
	if passport:
		print('22222')
		next_url = request.session.get('url_path',reverse('book:index'))
		print('33333')
		jres = JsonResponse({'res':1,'next_url':next_url})

		if remember == 'true':
			print('44444')
			jres.set_cookie('username',username,max_age=7*24*3600)
		else:
			print('55555')
			jres.delete_cookie('username')
		request.session['islogin'] = True
		request.session['username'] = username
		request.session['passport_id'] = passport.id
		print('66666')
		return jres
	else:
		return JsonResponse({'res':0})
def login(request):
	return render(request,'login/login.html')

@login_required
def user(request):
	passport_id = request.session.get('passport_id')

	addr = Address.object.get_default_address(passport_id=passport_id)

	books_li = []

	context = {
		'addr':addr,
		'page':'user',
		'book_li':books_li
	}
	return  render(request,'register/user_center_info.html',context)

books/templates/register/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-注册{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
			<div class="reg_slogan">学计算机  ·  来尚硅谷</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="#">登录</a>
			</div>
			<div class="reg_form clearfix">


				<form action="{% url 'user:register_handler' %}" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”尚硅谷书城用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
{% endblock body %}

books/templates/register/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="user_center_info.html" class="active">· 个人信息</a></li>
				<li><a href="user_center_order.html">· 全部订单</a></li>
				<li><a href="user_center_site.html">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ addr.recipient_name }}</li>
							<li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
							<li><span>联系地址：</span>{{ addr.recipient_addr }}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="book_type_list clearfix">
				<li>
					<a href="detail.html"><img src="images/book/book003.jpg"></a>
					<h4><a href="detail.html">Python Cookbook</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book004.jpg"></a>
					<h4><a href="#">Python高性能编程</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book005.jpg"></a>
					<h4><a href="#">Javascript高级程序设计</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book006.jpg"></a>
					<h4><a href="#">Javascript权威指南</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book007.jpg"></a>
					<h4><a href="#">Javascript语言精粹</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>
			</ul>
		</div>
		</div>
	</div>

{% endblock body %}