books/book/urls.py
from django.conf.urls import include, url
from book import views
urlpatterns = [
    url(r'^$', views.index, name='index'),  # 首页
    url(r'^detail/(?P<id>.*)$',views.detail,name='detail'),
    url(r'^list/(?P<type_id>.+)/(?P<page>.+)$',views.list,name='list'),
]

books/books/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('register.urls', namespace='user')),
    url(r'^tinymce/',include('book.urls',namespace='book')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
]

books/book/models.py
from django.db import models

# Create your models here.


from db.models import BaseModel
from tinymce.models import HTMLField
from book.enums import *

class BookManager(models.Manager):
	def get_book_by_type(self,type_id,limit=None,sort='default'):
		if sort == 'new':
			order_by = ('-create_time',)
		elif sort == 'hot':
			order_by = ('-sales',)
		elif sort == 'price':
			order_by = ('price',)
		else:
			order_by = ('-pk',)
		book_li = self.filter(type_id = type_id).order_by(*order_by)

		if limit:
			book_li = book_li[:limit]
		return book_li
	def get_books_by_id(self,books_id):
		try:
			books = self.get(id=books_id)
		except:
			books = None
		return books
class Book(BaseModel):
	book_type_chjoices = ((k,v) for k,v in BOOKS_TYPE.items())
	status_choices = ((k,v) for k,v in STATUS_CHOICE.items())

	type_id = models.SmallIntegerField(default=PYTHON,choices=book_type_chjoices)
	name = models.CharField(max_length=20,verbose_name='商品名称')
	desc = models.CharField(max_length=128,verbose_name='商品简介')
	price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='商品价格')
	unite = models.CharField(max_length=20,verbose_name='商品单位')
	stock = models.IntegerField(default=1,verbose_name='商品库存')
	sales = models.IntegerField(default=0,verbose_name='商品销量')
	detail = HTMLField(verbose_name='商品详情')
	image = models.ImageField(upload_to='books',verbose_name='商品图片')
	status = models.SmallIntegerField(default=ONLINE,choices=status_choices)

	object = BookManager()

	class Meta:
		db_table = 's_books'

books/book/views.py
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from book.models import Book
from book.enums import *
# Create your views here.


def index(request):
	'''显示首页'''
	# 查询每个种类的3个新品信息和4个销量最好的商品信息
	python_new = Book.object.get_book_by_type(PYTHON, 3, sort='new')
	python_hot = Book.object.get_book_by_type(PYTHON, 4, sort='hot')
	javascript_new = Book.object.get_book_by_type(JAVASCRIPT, 3, sort='new')
	javascript_hot = Book.object.get_book_by_type(JAVASCRIPT, 4, sort='hot')
	algorithms_new = Book.object.get_book_by_type(ALGORITHMS, 3, sort='new')
	algorithms_hot = Book.object.get_book_by_type(ALGORITHMS, 4, sort='hot')
	machinelearning_new = Book.object.get_book_by_type(MACHINELEARNING, 3, sort='new')
	machinelearning_hot = Book.object.get_book_by_type(MACHINELEARNING, 4, sort='hot')
	operatingsystem_new = Book.object.get_book_by_type(OPERATINGSYSTEM, 3, sort='new')
	operatingsystem_hot = Book.object.get_book_by_type(OPERATINGSYSTEM, 4, sort='hot')
	database_new = Book.object.get_book_by_type(DATABASE, 3, sort='new')
	database_hot = Book.object.get_book_by_type(DATABASE, 4, sort='hot')

	# 定义模板上下文
	context = {
		'python_new': python_new,
		'python_hot': python_hot,
		'javascript_new': javascript_new,
		'javascript_hot': javascript_hot,
		'algorithms_new': algorithms_new,
		'algorithms_hot': algorithms_hot,
		'machinelearning_new': machinelearning_new,
		'machinelearning_hot': machinelearning_hot,
		'operatingsystem_new': operatingsystem_new,
		'operatingsystem_hot': operatingsystem_hot,
		'database_new': database_new,
		'database_hot': database_hot,
	}

	return render(request,'book/book_details.html',context)
def detail(request,id):
	books = Book.object.get_books_by_id(books_id = id)
	if books is None:
		return redirect(reverse('book:index'))
	books_li = Book.object.get_book_by_type(type_id=books.type_id,limit=2, sort='new')
	context = {'books':books,'books_li':books_li}
	return render(request,'book/detail.html',context)

def list(request,type_id,page):
	sort = request.GET.get('sort','default')

	if int(type_id) not in BOOKS_TYPE.keys():
		return redirect(reverse('book:index'))

	books_li = Book.object.get_book_by_type(type_id=type_id,sort=sort)

	pagintor = Paginator(books_li,1)

	num_pages = pagintor.num_pages

	if page == '' or int(page) > num_pages:
		page = 1
	else:
		page = int(page)

	books_li = pagintor.page(page)

	if num_pages < 5:
		page = range(1, num_pages + 1)
	elif page <= 3:
		page = range(1, 6)
	elif num_pages - page <= 2:
		page = range(num_pages - 4, num_pages + 1)
	else:
		page = range(page - 2, page + 3)

	# 新品推荐
	books_new = Book.object.get_book_by_type(type_id=type_id, limit=2, sort='new')

	# 定义上下文
	type_title = BOOKS_TYPE[int(type_id)]
	context = {
		'books_li': books_li,
		'books_new': books_new,
		'type_id': type_id,
		'sort': sort,
		'type_title': type_title,
		'page': page
	}


	return render(request, 'book/list.html', context)

books/templates/book/book_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="python">Python</a></li>
			<li><a href="#model02" class="javascript">Javascript</a></li>
			<li><a href="#model03" class="algorithms">数据结构与算法</a></li>
			<li><a href="#model04" class="machinelearning">机器学习</a></li>
			<li><a href="#model05" class="operatingsystem">操作系统</a></li>
			<li><a href="#model06" class="database">数据库</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg" style="width: 240px; height: 135px;"></a>
			<a href="#"><img src="/static/images/adv02.jpg" style="width: 240px; height: 135px;"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">Python</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for python in python_new %}
				    <a href="#">{{ python.name }}</a>
				{% endfor %}


			</div>
			<a href="{% url 'book:list' type_id=1 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner01.jpg"></div>
			<ul class="book_list fl">
                {% for python in python_hot %}
                    <li>
                        <h4><a href="#">{{ python.name }}</a></h4>
                        <a href="{% url 'book:detail' python.id %}"><img src="/static/books/banner04.jpg"></a>
                        <div class="prize">{{  python.python }}</div>
                    </li>
                {% endfor %}

			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">Javascript</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for js in javascript_new %}
				    <a href="#">{{ js.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner02.jpg"></div>
			<ul class="book_list fl">
                
                {% for js in javascript_hot %}
                    <li>
                        <h4><a href="#">{{ js.name }}</a></h4>
                        <a href="{% url 'book:detail' js.id %}"><img src="{% static js.image %}"></a>
                        <div class="prize">{{ js.price }}</div>
                    </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">数据结构与算法</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for algo in algorithms_new %}
				    <a href="#">{{ algo.name }}</a>
				{% endfor %}


			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner03.jpg"></div>
			<ul class="book_list fl">

				{% for algo in algorithms_hot %}
                    <li>
                        <h4><a href="#">{{ algo.name }}</a></h4>
                        <a href="#"><img src="{% static algo.image %}"></a>
                        <div class="prize">¥{{ algo.price }}</div>
                    </li>
				{% endfor %}

			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">机器学习</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for mach in machinelearning_new %}
				    <a href="#">{{ mach.name }}</a>
				{% endfor %}


			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/books/banner04.jpg"></div>
			<ul class="book_list fl">

                {% for mach in machinelearning_hot %}
                    <li>
                        <h4><a href="#">{{ mach.name }}</a></h4>
                        <a href="#"><img src="{% static mach.image %}"></a>
                        <div class="prize">¥ {{ mach.price }}</div>
                    </li>
                {% endfor %}

			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">操作系统</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for oper in operatingsystem_new %}
				    <a href="#">{{ oper.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner05.jpg"></div>
			<ul class="book_list fl">

				{% for oper in operatingsystem_hot %}
				    <li>
                        <h4><a href="#">{{ oper.name }}</a></h4>
                        <a href="#"><img src="{% static oper.image %}"></a>
					    <div class="prize">¥ {{ oper.price }}</div>
				    </li>
				{% endfor %}

			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">数据库</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for data in database_new %}
				    <a href="#">{{ data.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner06.jpg"></div>
			<ul class="book_list fl">

                {% for data in database_hot %}
                    <li>
                        <h4><a href="#">{{ data.name }}</a></h4>
                        <a href="#"><img src="{% static data.image %}"></a>
                        <div class="prize">¥ {{ data.price }}</div>
                    </li>
                {% endfor %}

			</ul>
		</div>
	</div>
{% endblock body %}

books/templates/book/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}

{% block topfiles %}
    <script>
        $(function () {
            update_total_price();
            // 计算总价
            function update_total_price() {
                // 获取商品的价格和数量
                books_price = $('.show_pirze').children('em').text();
                books_count = $('.num_show').val();
                // 计算商品的总价;
                books_price = parseFloat(books_price);
                books_count = parseInt(books_count);
                total_price = books_price * books_count;
                // 设置商品总价
                $('.total').children('em').text(total_price.toFixed(2) + '元')
            }

            // 商品增加
            $('.add').click(function () {
                // 获取商品的数量
                books_count = $('.num_show').val();
                // 加1
                books_count = parseInt(books_count) + 1;
                // 重新设置值
                $('.num_show').val(books_count);
                // 计算总价
                update_total_price()
            });

            // 商品减少
            $('.minus').click(function () {
                // 获取商品的数量
                books_count = $('.num_show').val();
                // 加1
                books_count = parseInt(books_count) - 1;
                if (books_count == 0){
                    books_count = 1
                }
                // 重新设置值
                $('.num_show').val(books_count);
                // 计算总价
                update_total_price()
            });

            // 手动输入
            $('.num_show').blur(function () {
                // 获取商品的数量
                books_count = $(this).val();
                // 数据校验
                if (isNaN(books_count) || books_count.trim().length == 0 || parseInt(books_count) <= 0 ){
                    books_count = 1
                }
                // 重新设置值
                $('.num_show').val(parseInt(books_count));
                // 计算总价
                update_total_price()
            })


        })
    </script>
{% endblock topfiles %}
{% block body %}

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">Python</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="book_detail_con clearfix">
		<div class="book_detail_pic fl"><img src="{% static books.image %}"></div>
		<div class="book_detail_list fr">
			<h3>{{ books.name }}</h3>
			<p>{{ books.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ books.price }}</em></span>
				<span class="show_unit">单  位：{{ books.unite }}册</span>
			</div>
			<div class="book_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>{{ books.price }}</em></div>
			<div class="operate_btn">
				{% csrf_token %}
                    <a href="javascript:;" class="buy_btn">立即购买</a>
                    <a href="javascript:;" books_id="{{ books.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">

                <div class="new_book">
				<h3>新品推荐</h3>
				<ul>
                    {% for book in books_li %}
					<li>
						<a href="#"><img src="{% static book.image %}"></a>
						<h4><a href="#">{{ book.name }}</a></h4>
						<div class="prize">￥{{ book.book }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>


		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd >{{ books.detail | safe }}</dd>
				</dl>
			</div>

		</div>
	</div>
    <div class="add_jump"></div>
{% endblock body %}
{% block bottomfiles %}
    <script>
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $('#add_cart').click(function(){
        // 获取商品的id和商品数量
        books_id = $(this).attr('books_id')
        books_count = $('.num_show').val()
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        // 发起请求，访问/cart/add/, 进行购物车数据的添加
        params = {
            'books_id': books_id,
            'books_count': books_count,
            'csrfmiddlewaretoken': csrf
        }

        $.post('/cart/cart_add/', params, function (data) {
            if (data.res == 5){
                // 添加成功
                $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                $(".add_jump").stop().animate({
                    'left': $to_y+7,
                    'top': $to_x+7},
                    "fast", function() {
                        $(".add_jump").fadeOut('fast',function(){
                            // 获取原有show_count的值
                            count = $('#show_count').html()
                            count = parseInt(count) + parseInt(books_count)
                            $('#show_count').html(count);
                        });
                });
            }
            else {
                // 添加失败
                alert(data.errmsg)
            }
        })
    })

    </script>
{% endblock %}

books/templates/book/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-商品列表{% endblock title %}
{% block body %}

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">Python</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>

					{% for book_new in books_new %}
                        <li>
                            <a href="#"><img src="{% static book_new.image %}"></a>
                            <h4><a href="#">{{ book_new.name }}</a></h4>
                            <div class="prize">￥{{ book_new.price }}</div>
                        </li>
					{% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="book_type_list clearfix">
				<li>
					<a href="detail.html"><img src="images/book/book003.jpg"></a>
					<h4><a href="detail.html">Python Cookbook</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book004.jpg"></a>
					<h4><a href="#">Python高性能编程</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book005.jpg"></a>
					<h4><a href="#">Javascript高级程序设计</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book006.jpg"></a>
					<h4><a href="#">Javascript权威指南</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book007.jpg"></a>
					<h4><a href="#">Javascript语言精粹</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book008.jpg"></a>
					<h4><a href="#">Javascript DOM编程精粹</a></h4>
					<div class="operate">
						<span class="prize">￥9.50</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book009.jpg"></a>
					<h4><a href="#">数据结构与算法分析</a></h4>
					<div class="operate">
						<span class="prize">￥3.30</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book010.jpg"></a>
					<h4><a href="#">算法导论</a></h4>
					<div class="operate">
						<span class="prize">￥5.00</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book011.jpg"></a>
					<h4><a href="#">算法</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book012.jpg"></a>
					<h4><a href="#">计算机程序设计艺术</a></h4>
					<div class="operate">
						<span class="prize">￥25.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>
				<li>
					<a href="#"><img src="images/book/book013.jpg"></a>
					<h4><a href="#">机器学习</a></h4>
					<div class="operate">
						<span class="prize">￥4.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>
				<li>
					<a href="#"><img src="images/book/book014.jpg"></a>
					<h4><a href="#">机器学习实战</a></h4>
					<div class="operate">
						<span class="prize">￥3.50</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>
				<li>
					<a href="#"><img src="images/book/book001.jpg"></a>
					<h4><a href="#">Python核心编程</a></h4>
					<div class="operate">
						<span class="prize">￥3.90</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>
				<li>
					<a href="#"><img src="images/book/book002.jpg"></a>
					<h4><a href="#">Python学习手册</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>
			</ul>

			<div class="pagenation">
				<a href="#"><上一页</a>
				<a href="#" class="active">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">5</a>
				<a href="#">下一页></a>
			</div>
		</div>
	</div>
{% endblock body %}